---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    - homebrew/dupes
    - homebrew/versions
#    - homebrew/homebrew-php
    brew_packages:
    - php53
    - php54
    - php55
    - php56
    - php53-xdebug
#    - php54-xdebug
#    - php55-xdebug
#    - php56-xdebug
    - brew-php-switcher
# https://github.com/philcook/brew-php-switcher
# Syntax: brew-php-switcher 54 for php 5.4
    - php-code-sniffer
    - p7zip
    - git
    - zsh
    - vim
    - the_silver_searcher
    - ctags
    - reattach-to-user-namespace
    - tmux
    - mysql
    - watch
    - wget
    cask_packages:
    - java
    - font-inconsolata-for-powerline
    - filezilla
    - iterm2
    - macvim
    - firefox
    - google-chrome
    - google-hangouts
    - jdiskreport
    - netbeans-php #didn’t work
    - python
    - pycharm-ce
    - phpstorm  
    - mysqlworkbench
    - sublime-text
    - vagrant
    - vagrant-manager
    - virtualbox
    - textmate
