---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    brew_packages:
    - p7zip
    - git
    - zsh
    - vim
    - the_silver_searcher
    - ctags
    - reattach-to-user-namespace
    - tmux
    - mysql
    - watch
    - wget
    cask_packages:
    - font-inconsolata-for-powerline
    - iterm2
    - macvim
    - firefox
    - google-chrome
    - google-hangouts
    - phpstorm
    - mysqlworkbench
    - sublime-text
    - vagrant
    - virtualbox
    - textmate