---
# Here we describe every software we may want to install
- hosts: all
  roles:
#   - role: osxc.packages
#     brew_taps:
#     - caskroom/fonts
#     - homebrew/dupes
#     - homebrew/versions
#     brew_packages:
#     - memcached
#     - php53
#     - php54
#     - php55
#     tasks:
#     - name: Link php
#       shell: brew link php54
#     brew_packages:
#     - php54-xdebug
#     - php54-memcached
#     - php54-apc
#     - brew-php-switcher
# # https://github.com/philcook/brew-php-switcher
# # Syntax: brew-php-switcher 54 for php 5.4
#     - php-code-sniffer
#     - p7zip
#     - git
#     - zsh
#     - vim
#     - the_silver_searcher
#     - ctags
#     - reattach-to-user-namespace
#     - tmux
#     - mysql
#     - watch
#     - wget
#     cask_packages:
#     - java
#     - font-inconsolata-for-powerline
#     - filezilla
#     - iterm2
#     - firefox
#     - google-chrome
#     - google-hangouts
#     - jdiskreport
#     - netbeans-php #didn’t work
#     - python
#     - pycharm-ce
#     - phpstorm
#     - mysqlworkbench
#     - sublime-text
#     - vagrant
#     - vagrant-manager
#     - virtualbox
#     - textmate