---
galaxy_info:
  author: Richard Alexander Allen
  description: Ansible role that installs Drupal coding standards for PHP Code Sniffer.
  license: GPLv2
  min_ansible_version: 1.2

  categories:
  - development
  - web

dependencies:
  - AlexanderAllen.Composer
  - AlexanderAllen.CodeQuality

